version: "3"

services:
  db-postgres-filme:
    image: postgres:alpine
    ports:
      - "5433:5432"
    container_name: "db-postgres-filme"
    restart: always
    volumes:
      - ./banco-de-dados-filme:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpg

volumes:
 banco-de-dados-filme: